name: deploy

on:
  push:
    branches: ["main"]

env:
  REGISTRY: cachac
  IMAGE_NAME: rest_api

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: code checkout

      - name: docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v3
        with: 
          push: true
          build-args: | 
            APP_ENV=${{ secrets.APP_ENV }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}:latest

  
  loadTest:
    name: Load Testing
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: Set up
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: |
          npm install -g artillery
          npm install --save-dev artillery-plugin-ensure

      - name: Run container
        run: |
          docker run -d --name rest-api -p 3000:3000 ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Run load test
        run: | 
          set -e  # Detiene el workflow si la prueba de carga falla.
          artillery run loadTest/basic.yaml || exit 1




