name: dast

on:
  push:
    branches: ["main"]

permissions:
  issues: write

env:
  REGISTRY: cachac
  IMAGE_NAME: rest_api

jobs:
  dast:
    name: ZAP - DAST Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout code

      - name: run api
        run: |
          npm install
          npm run dev&

      - name: ZAP Scan
        uses: zaproxy/action-api-scan@v0.7.0
        with:
          target: 'http://localhost:3000/search?q=123'
          artifact_name: 'zap-scan-report'